name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v4

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Install Playwright browsers
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # 5. Run tests
      - name: Run Playwright tests
        run: npx playwright test
        continue-on-error: true

      # 6. Upload test report (Allure raw results)
      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: allure-results

      # 7. Generate Allure report
      - name: Generate Allure report
        run: npx allure generate allure-results --clean -o allure-report

      # 8. Upload HTML report
      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report
